<?php
/**
 * SalesTaxJurisdictionTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Ebay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Metadata API
 *
 * The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.
 *
 * The version of the OpenAPI document: v1.4.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ebay\Sell\Metadata\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SalesTaxJurisdictionTest Class Doc Comment
 *
 * @category    Class
 * @description A unique ID for a sales tax jurisdiction.
 * @package     Ebay\Sell\Metadata
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SalesTaxJurisdictionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SalesTaxJurisdiction"
     */
    public function testSalesTaxJurisdiction()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sales_tax_jurisdiction_id"
     */
    public function testPropertySalesTaxJurisdictionId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
